name: 'crowdin'
description: 'Upload/Download crowdin translations'
inputs:
  crowdin_action:
    description: upload/download
    required: true
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.crowdin_action }}
