name: 'crowdin'
description: 'Upload/Download crowdin translations'
inputs:
  working-directory:
    description: Optional working-directory folder where the command is executed
    default: '.'
    required: false
  crowdin-action:
    description: Crowdin action to be executed [upload, download]
    required: true
  dry-run:
    description: Run Crowdin action in dry-run mode [true, false]
    default: 'false'
    required: false
runs:
  using: docker
  image: 'Dockerfile'
